name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - published

env:
  docker_tag: ${{ github.event_name != 'release' && 'test' || 'latest' }}

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.repository == 'Kaiede/docker-minecraft-bedrock-backup'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}      
      
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +%s)"
        
    - name: Build and push
      run: bash build.sh ${{ env.docker_tag }} main ${{ github.event_name != 'pull_request' && 'push' || 'nopush' }}      
    
      
    
